# Generated by Django 3.2.8 on 2024-05-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='banner',
            field=models.ImageField(blank=True, default='noBanner.png', upload_to=''),
        ),
    ]
