# Generated by Django 3.2.8 on 2024-04-24 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0003_auto_20240416_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='playlist',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='playlists.playlist'),
        ),
    ]
