# Generated by Django 3.2.8 on 2024-04-27 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0007_alter_playlist_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('playlists.playlist',),
        ),
    ]
