# Generated by Django 3.2.8 on 2024-05-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0011_auto_20240509_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='parent_banner',
            field=models.ImageField(blank=True, default='noBanner.png', null=True, upload_to=''),
        ),
    ]
